import pandas as pd
from functools import reduce
import pprint
from latex import build_pdf, escape

def get_info(column_name, input_dict):
    info = list(input_dict.values())
    output = ''
    if len(info) == 1:
        output += r'    \item[' + column_name + '] ' + escape(str(info[0]))
    elif len(info) > 1:
        output += r'    \item[' + column_name + r']  \hfill' + r'  \begin{itemize}'
        for item in info:
            output += r'  \item ' + escape(str(item))
        output += r'  \end{itemize}'
    return output

# def create_latex_section(column_name, info):
#     return r'''
#           \item[INSERT_COLUMN_NAME_HERE] INSERT_INFO_HERE
#           \begin{itemize}
#             \item INSERT_ITEM_HERE
#           \end{itemize}
#             '''.replace('INSERT_COLUMN_NAME_HERE', column_name).replace('INSERT_INFO_HERE', info)
# def create_latex_list(prez_info):
#     start = r'  \begin{itemize}'
#     middle = ''
#     for info in prez_info:
#         middle += r'  \item ' + info
#     end = r'  \end{itemize}'
#     return start + middle + end



df = pd.read_excel('/home/yuxuan/Downloads/Presidents database.xlsx', dtype=str, index_col=None, sheet_name=None)

latex_start = r'''
    \documentclass[11pt]{article}
    \pagestyle{plain}
    \usepackage[letterpaper, margin=1in]{geometry}
    \usepackage[utf8]{inputenc}
    \usepackage{helvet}

    \begin{document}

    \title{\textbf{Presidents Packet}}
    \author{Generated by Yuxuan's Prez Worksheet Creator}
    \date{\today}
    \maketitle
    '''

latex_end = r'    \end{document}'

latex_prez = r'''
    \section{INSERT_PRESIDENT_HERE}
      \begin{description}
        INSERT_SECTION_HERE
      \end{description}
      
    \pagebreak
'''



prez_info = []
for prez_num in range(1, 45):
    temp_info = []
    for sheet_name in df:
        temp_info.append(df[sheet_name][df[sheet_name]['Prez Number'] == str(prez_num)].to_dict())
    prez_info.append((prez_num, temp_info))

# print(prez_info)

prez_latex = latex_start

for prez, info in prez_info:
    first = True
    prez_latex += r'''
                    \section{INSERT_PRESIDENT_HERE}
                    \begin{description}
                    '''
    for prez_dict in info:
        for column_name, prez_info in prez_dict.items():
            if first and column_name == 'Name':
                prez_latex = prez_latex.replace('INSERT_PRESIDENT_HERE', list(prez_info.values())[0])
                first = False
            elif column_name != 'Prez Number':
                prez_latex += get_info(column_name, prez_info)
                # print(column_name + ':', get_info(prez_info))
    prez_latex += r'''
                    \end{description}
                    \pagebreak
                            '''
prez_latex += latex_end

print(prez_latex)
with open('out.txt', 'w+') as f:
    f.write(prez_latex)

pdf = build_pdf(prez_latex)
pdf.save_to('out.pdf')

